### PR TITLE
Trimmed

### PR DESCRIPTION
**Pull request by ForgivenNin**
- Parts PHP & HTML into separate files
- Removed `if` statement (Form's `<input>` fields are already set to be `required`).
- Removed `$validpw` (Unused in script).
- Removed `if(isset($mail)){echo $mail;}` (Already indicator if email was sent).
- Updated `README.md`

### CODE REVIEW

**Comment by ForgivenNin** [comment]
I would go ahead and re-add `if(isset($mail)){echo $mail;}`, and I would have never deleted it to begin with, but because of the split (HTML + PHP) instead of just one `.php` file, I had to remove it. However, I could try writing a `.js` script that can echo the email written once it is sent.

@cookiedragon234 what do you mean by
> Also seperate the link from the full stop...

**Comment by cyruscook** [comment]
If you've tested it and it works thats fine

**Comment by ForgivenNin** [comment]
@cookiedragon234 & @cyruscook I decided that it would be good for me to keep the original PHP file as the GitHub pages site, along with the recent changes. I didn't know if I should send a pull request if you wanted to do the same.

Also, how did you make that possible (for PHP to be hosted) initially? I've heard that only static things could be accessed on the GitHub servers.

**Comment by cyruscook** [comment]
It isnt hosted on github pages, its hosted on my personal server.

**Pull request merged**
